name: allervie-analytics-dashboard
region: nyc
services:
- name: api
  github:
    branch: main
    repo: YOUR_USERNAME/allervie-dashboard-app
    deploy_on_push: true
  http_port: 5002
  routes:
  - path: /
    preserve_path_prefix: true
  health_check:
    http_path: /api/health
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: FLASK_APP
    value: backend/app.py
  - key: FLASK_ENV
    value: production
  - key: ALLOW_MOCK_DATA
    value: "false" 
  - key: ALLOW_MOCK_AUTH
    value: "false"
  - key: ENVIRONMENT
    value: "production"
  - key: GOOGLE_ADS_CLIENT_ID
    scope: RUN_TIME
    value: "YOUR_CLIENT_ID.apps.googleusercontent.com"
  - key: GOOGLE_ADS_CLIENT_SECRET
    type: SECRET
    scope: RUN_TIME
    value: "YOUR_CLIENT_SECRET"
  - key: GOOGLE_ADS_DEVELOPER_TOKEN
    type: SECRET
    scope: RUN_TIME
    value: "YOUR_DEVELOPER_TOKEN"
  - key: GOOGLE_ADS_LOGIN_CUSTOMER_ID
    scope: RUN_TIME
    value: "YOUR_LOGIN_CUSTOMER_ID"
  - key: GOOGLE_ADS_REFRESH_TOKEN
    type: SECRET
    scope: RUN_TIME
    value: "YOUR_REFRESH_TOKEN"
  - key: GOOGLE_ADS_USE_PROTO_PLUS
    value: "true"
  - key: GOOGLE_ADS_API_VERSION
    value: "v17"
  - key: TOKEN_AUTO_REFRESH_ENABLED
    value: "true"
  - key: AUTO_REFRESH_INTERVAL_MINUTES
    value: "30"
  - key: CLIENT_CUSTOMER_ID
    value: "YOUR_CLIENT_CUSTOMER_ID"
  - key: USE_ENHANCED_REFRESH
    value: "true"
  - key: APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}