name: allervie-analytics-dashboard
region: nyc
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: jhillbht/allervie-dashboard-app
  http_port: 5002
  routes:
  - path: /
    preserve_path_prefix: true
  health_check:
    http_path: /api/health
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: FLASK_APP
    value: backend/app.py
  - key: FLASK_ENV
    value: production
  - key: ALLOW_MOCK_DATA
    value: "false" 
  - key: ALLOW_MOCK_AUTH
    value: "false"
  - key: ENVIRONMENT
    value: "production"
  - key: TOKEN_AUTO_REFRESH_ENABLED
    value: "true"
  - key: AUTO_REFRESH_INTERVAL_MINUTES
    value: "30"
  - key: USE_ENHANCED_REFRESH
    value: "true"
  - key: USE_REAL_ADS_CLIENT
    value: "true"
  - key: APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: GOOGLE_ADS_YAML
    scope: RUN_TIME
    type: SECRET
    value: Y2xpZW50X2lkOiAyMjA4MzYxMzc1NC1kMW9tZWcyOTU4dnJzbmRwcWcydjFqcDBuY203c3IyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQpjbGllbnRfc2VjcmV0OiBHT0NTUFgtNi1PX0hpdDlmYko4TWVjRUxtbDZ6VW95bVhmVQpkZXZlbG9wZXJfdG9rZW46IEVrWEZFTmphaFNEbnBOUlpKaFdBQXcKbG9naW5fY3VzdG9tZXJfaWQ6IDgxMjc1Mzk4OTIKcmVmcmVzaF90b2tlbjogMS8vMGYxeDZydEdQdmozYUNnWUlBUkFBR0E4U053Ri1MOUlyMmJ6SUhYTUlOYmVxWU9XbkZxNGcwSXFmbXhJcVp4cndfVUlWUHlTZnprUk5PbUVOVHV0VEdhNGtEUlk0SDlVTlhmawp1c2VfcHJvdG9fcGx1czogdHJ1ZQphcGlfdmVyc2lvbjogdjE3Cg==
